[build]
builder = "nixpacks"

[build.env]
YOUTUBE_DL_SKIP_PYTHON_CHECK = "1"

[deploy]
startCommand = "node index.js"

[[deploy.preDeployCommands]]
command = "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ./yt-dlp && chmod +x ./yt-dlp"
